# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff24f83256061f1a97a3fd35196bc541151d1af5d38a6aa51b5c9acdc3271ae4e010eedac3a8cdf2a0f048de1b096b17f3276fea9e8724cc7c5fd0a241dba7a2

test:
  secret_key_base: fcbc7bd17de996f210becab2dd36c21627555916b916cb54f9c1265eb3f6e5829b4120fbf517a8d9a38ca2428c966e8a2ec7ec20d05cf1d6d77ab51ef0ab0b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
